### ISSUE TITLE
Create SHACL based on real data

### ISSUE THREAD

**Issue by natan-cox-cognizone** [cognizone/asquare#84]
We want to be able to create SHACLs based on existing data. This will be convenient because it can guarantee all properties to be present.

Features to be included
* support for NodeShape and PropertyShape
* sh:targetClass
* sh:path
* sh:minCount
* sh:maxCount
* sh:nodeKind
* sh:datatype
* sh:class

**Comment by alexey-lukashov** [comment]
May be it could be reduced to json schema -> shacl, because we can do RDF -> Json -> JSON Schema -> Shacl
we have tools for rdf->json and json->json schema, only the last part is remaining

**Comment by natan-cox-cognizone** [comment]
> May be it could be reduced to json schema -> shacl, because we can do RDF -> Json -> JSON Schema -> Shacl we have tools for rdf->json and json->json schema, only the last part is remaining

Not sure if this is simpler. Btw @alexey-lukashov PR is almost there ;)
